name: Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    # Don't run on forks
    if: github.repository == 'jack-weilage/antithrow'
    permissions:
      contents: write # To create releases
      id-token: write # OIDC trusted publishing
      pull-requests: write # Create changeset pull request

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up Bun.sh
        uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2

      - name: Install dependencies
        run: bun install
        
      - name: Run changesets
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
